export type Language = 'zh' | 'en'
export type Bilingual = { zh: string; en: string }
export const words = (zh: string, en: string): Bilingual => ({ zh, en })
export type ParameterChoice = { value: string; label: Bilingual }
export type Parameter = { key: string; label: Bilingual; help: Bilingual; placeholder?: string; flag?: boolean; choices?: ParameterChoice[]; inputType?: 'number'|'text'|'password'; min?: number; max?: number; step?: number; defaultValue?: Bilingual; readOnly?: boolean }
export type ParameterGroup = { title: Bilingual; fields: Parameter[]; advanced?: boolean }
export const field = (key: string, zh: string, en: string, helpZh: string, helpEn: string, placeholder?: string, control: Partial<Pick<Parameter,'inputType'|'min'|'max'|'step'|'choices'|'defaultValue'>> = {}): Parameter => ({ key, label: words(zh,en), help: words(helpZh,helpEn), placeholder, ...control })
export const flag = (key: string, zh: string, en: string, helpZh: string, helpEn: string): Parameter => ({ ...field(key,zh,en,helpZh,helpEn), flag:true })
export const choice = (key: string, zh: string, en: string, helpZh: string, helpEn: string, choices: ParameterChoice[], defaultValue?: Bilingual): Parameter => ({ ...field(key,zh,en,helpZh,helpEn), choices, defaultValue })
const numeric = (key: string, zh: string, en: string, helpZh: string, helpEn: string, min: number, max: number, defaultValue: Bilingual, placeholder?: string): Parameter => ({ ...field(key,zh,en,helpZh,helpEn,placeholder), inputType:'number', min, max, step:1, defaultValue })
export const identityHelp = {
  name: words('用于托盘菜单和配置列表的显示名称，可与 API model ID 不同。重命名不会移动模型文件。', 'The display name in the tray and profile list. It may differ from the API model ID. Renaming does not move the model file.'),
  model: words('选择已扫描到的 .ninfer 主文件。引擎启动时才加载权重到 GPU；扫描不会加载 GPU。相对路径从模型包根目录解析。更换文件后应核对上下文和量化格式。', 'Choose the scanned .ninfer entry file. GPU weights are loaded only when the engine starts; scanning does not load the GPU. Relative paths start at the package root. Check context and quantization when changing models.'),
  engine: words('实际运行的 ninfer-serve.exe 路径；相对路径从模型包根目录解析。不同引擎支持的参数可能不同。当前 engine 目录中的版本支持严格驻留检查。', 'Path to the ninfer-serve.exe to run, relative to the package root or absolute. Supported options depend on the engine. The build in the engine directory supports strict residency checks.'),
  json: words('直接编辑完整 CLI 参数字典：键为 --参数名，字符串为参数值，null 表示只传这个开关，删除键表示不传。保存前会验证 JSON 对象；切换语言不会改变内容。未指定 --request-log-jsonl 时，管理器自动创建请求日志；也可以填写自己的路径。请求日志、磁盘 KV 与前缀缓存文件的相对路径从当前数据目录解析，默认在 LOCALAPPDATA 下；绝对路径保持原样。未知参数的语义请查所选引擎 --help。', 'Edit the complete CLI argument object: keys are --option names, strings are values, null passes a flag without a value, and deleting a key omits it. JSON is validated before saving; changing language does not alter it. The manager creates a request log when --request-log-jsonl is omitted, or you can choose a custom path. Relative request-log, disk-KV and prefix-cache output paths start at the active data directory, normally under LOCALAPPDATA; absolute paths are unchanged. Consult the selected engine’s --help for unknown options.'),
  environment: words('仅为模型子进程设置环境变量；字符串覆盖，null 清除继承值。NINFER_PREFILL_ALIGN=0 保持填写的 chunk；NINFER_PROMPT_FAST 影响 prompt 内核选择；CUDA_LAUNCH_BLOCKING=1 强制同步，通常会变慢。不要把未知变量当作性能开关。', 'Environment overrides for the model process only: strings set a value; null removes an inherited value. NINFER_PREFILL_ALIGN=0 keeps the requested chunk. NINFER_PROMPT_FAST affects prompt-kernel selection. CUDA_LAUNCH_BLOCKING=1 forces synchronization and usually slows execution. Unknown variables are not assumed to improve performance.'),
}
export const strictMemoryHelp = {
  reserve: words('严格模式启动时额外申请并验证的显存余量，随后释放。增大可给运行留出更多空间，但可用 KV 容量减少；0 不额外验证余量。它不限制 Host cache。默认 64 MiB，对应 strict 的第一个数字。','Extra VRAM allocated and verified at startup in strict mode, then released. More headroom leaves operating room but reduces KV capacity; zero skips the extra reserve check. It does not limit Host cache. The default is 64 MiB, the first number in strict.'),
  step: words('严格模式自动容量探测在初始大块后以这个步长逼近边界，范围 1–16384 MiB。更小更细但探测可能更慢，0 无效。正式 device arena 仍是连续分配。默认 128 MiB，对应 strict 的第二个数字。','After the initial large allocation, strict-mode automatic capacity probing approaches the boundary with this step, from 1 to 16384 MiB. Smaller steps are finer but may be slower; zero is invalid. Final device arenas remain contiguous. The default is 128 MiB, the second number in strict.'),
}
export const groups: ParameterGroup[] = [
 { title:words('API 与上下文','API and context'), fields:[
  field('--model-id','API 模型名称','API model ID','客户端请求中的 model 字段必须使用这个名称。多个配置可以共用一个名称，但本管理器同时只启动一个模型。修改不会重命名权重文件。','Clients use this name in the request’s model field. Profiles may share a name; this manager runs one model at a time. It does not rename model files.'),
  field('--host','API 监听地址','API host','模型 API 的监听地址。127.0.0.1 仅本机；0.0.0.0 允许局域网访问，启动后自动显示局域网 API 地址。这不是管理网页地址，也不会自动开放防火墙。','Model API bind address: 127.0.0.1 for this computer, or 0.0.0.0 for LAN access with an automatically detected LAN API URL. Separate from the management website; does not open the firewall.','127.0.0.1', {choices:[{value:'',label:words('管理器默认 · 127.0.0.1','Manager default · 127.0.0.1')},{value:'127.0.0.1',label:words('127.0.0.1 · 本机','127.0.0.1 · local only')},{value:'0.0.0.0',label:words('0.0.0.0 · 局域网','0.0.0.0 · LAN')}]}),
  field('--port','API 端口','API port','客户端连接模型的端口，范围 1–65535。留空时管理器使用 18081（引擎单独启动的默认值是 8080）。需与管理网页端口及其他进程不同；更改后客户端也需要更新 API base。0 不是自动选端口。','The model API port, from 1 to 65535. When omitted, the manager uses 18081; the standalone engine defaults to 8080. It must differ from the management port and other listeners. Update clients’ API base after changing it. Zero does not select a port automatically.','18081', {inputType:'number',min:1,max:65535,step:1,defaultValue:words('18081 · 管理器默认','18081 · manager default')}),
  field('--max-context','最大上下文 · tokens','Context limit · tokens','单个请求可容纳的总 token 上限，包含输入、历史、思考和回答；1K=1024。留空时管理器使用 163840（160K），引擎单独启动的默认值是 8192。增大通常需要更多 KV 显存。0 无效。这里单独编辑上下文，不自动改 KV 容量，请确保 KV 容量足够。','The per-request total token ceiling, including input, history, reasoning and answer; 1K=1024. When omitted, the manager uses 163840 (160K); the standalone engine defaults to 8192. Increasing it generally needs more KV memory. Zero is invalid. This field does not rewrite KV capacity; make sure the pool covers it.','163840', {inputType:'number',min:1,max:2147483647,step:1,defaultValue:words('163840 · 管理器默认','163840 · manager default')}),
  field('--kv-capacity','KV 池容量 · tokens / auto','KV capacity · tokens / auto','物理 KV 缓存总容量，应不小于最大上下文，按 64-token 页对齐。auto 随显存策略规划：default 按 CUDA free，strict 做驻留探测；mixed 最多规划每并发一个完整上下文窗口，不额外填满空闲前缀缓存。增大容量增加内存占用。0 无效，auto 不提高单请求上下文上限，也不保证分配成功。','Physical KV capacity must cover the context limit and rounds to 64-token pages. With auto, default uses CUDA free, strict probes residency, and mixed budgets at most one full context window per concurrent request, without filling extra prefix-cache space. More capacity uses more memory. Zero is invalid. Auto neither raises the context limit nor guarantees successful allocation.','163840 / auto'),
  field('--max-concurrency','并行请求数','Concurrent requests','同时执行的请求数，范围 1–8。单个 Codex agent 通常设 1；增大会增加状态与显存开销，可能降低单请求速度。ngram 草稿大于 15 时必须为 1。0 无效。','Requests executed together, from 1 to 8. One Codex agent usually uses 1. Higher values require more state and VRAM and may reduce single-request speed. Ngram drafts above 15 require 1. Zero is invalid.','1', {inputType:'number',min:1,max:8,step:1,defaultValue:words('1','1')}),
  field('--default-max-tokens','默认最大输出 · tokens','Default output limit · tokens','仅在请求没有显式指定输出上限时使用；思考和回答都计入输出。留空采用引擎默认 8192；显式填写 0 不设独立输出上限，仍受剩余上下文限制，并非无限上下文。较小值可控制等待时间，但可能截断回答。','Used only when a request omits its output limit. Both reasoning and answer tokens count. Omitting this option uses the engine default of 8192; explicit zero removes this separate cap but generation still ends when context is exhausted. Smaller limits shorten waits but may truncate an answer.','0', {inputType:'number',min:0,max:2147483647,step:1,defaultValue:words('8192 · 显式填 0 才不设独立上限','8192 · enter 0 explicitly for no separate cap')}),
 ]},
 { title:words('显存与缓存','GPU memory and cache'), fields:[
  field('--prefill-chunk','预填充块大小 · tokens','Prefill chunk · tokens','每批读取多少输入 token，应为 128 的倍数。更大可能提高预填充吞吐，也增加临时显存；更小可能降低峰值占用，但不一定更快。0 无效。是否自动对齐还受 NINFER_PREFILL_ALIGN 影响。','Input tokens processed per chunk; use a multiple of 128. Larger chunks may improve prefill throughput but require more temporary VRAM. Smaller chunks may reduce peaks, not necessarily latency. Zero is invalid. NINFER_PREFILL_ALIGN controls automatic alignment.','1024', {inputType:'number',min:128,max:2147483520,step:128,defaultValue:words('1024','1024')}),
  field('--kv-dtype','KV 缓存格式','KV cache format','保存注意力历史的格式。rk8v4 是当前已验证路线；rk4v4 / rk4v4-e8 更省显存，但精度和性能需要实测。更换会影响容量及缓存兼容性，不会改变权重量化文件。','Storage format for attention history. rk8v4 is the currently validated route. rk4v4 / rk4v4-e8 use less VRAM but need quality and speed validation. Changing it affects cache size and compatibility, not the weight file.','rk8v4', {choices:[{value:'',label:words('引擎默认 · bf16','Engine default · bf16')},...['bf16','int8','fp8','rk8v4','rk4v4','rk4v4-e8','rk2v4-e8','nvfp4','k8v4'].map(value=>({value,label:words(value,value)}))]}),
  field('--cuda-memory-policy','显存分配策略','GPU memory policy','default 保持 CUDA free 容量规划和原分配行为，也不保证绝不使用共享系统内存。mixed 允许超过 CUDA free 尝试分配；显存不足时允许 Windows 用系统内存承接 CUDA 设备数据，驱动决定放置，并非强制分配到 Shared。可能变慢，分配仍可能失败。strict 自动选择所需上下文缓存实现并检查实际驻留，Shared 超出基线会拒绝容量或后续请求。strict 默认余量/步长为 64/128 MiB，也可使用 strict-N-N。mixed/strict 仅支持 Windows 单 GPU 纯文本，不能与 WDDM D3D12 或显式 KV headroom 参数组合。CPU Host cache 独立配置，不属于显存不足时的系统内存借用。','default keeps CUDA-free capacity planning and the original allocation behavior; it does not guarantee that shared system memory will never be used. mixed may attempt allocation beyond CUDA free. When VRAM is insufficient, Windows may use system RAM for CUDA device data; the driver decides placement, rather than forcing allocation into Shared. Performance may decrease and allocation may still fail. strict automatically selects the required context-cache implementation and checks residency, rejecting capacity or later requests if Shared exceeds its baseline. strict uses a 64/128 MiB reserve/step by default, or strict-N-N. mixed/strict require Windows, one GPU and text-only inference and cannot use WDDM D3D12 or explicit KV headroom options. CPU Host cache is independent and is not system-RAM borrowing caused by insufficient VRAM.','strict'),
  field('--cuda-graph-allowance-mib','Graph 启动预算 · MiB','Graph startup budget · MiB','容量规划为 CUDA Graph 驱动状态预留的预算，不是 Graph 实际显存上限，也不会把 Graph 强制压到此大小。0 表示按执行路线自动估算；减小可释放规划预算，但可能使启动布局太紧。','Budget withheld during capacity planning for CUDA Graph driver state. It is neither a hard cap nor a command to shrink Graph allocations. Zero estimates it from execution profiles. Reducing it frees planned capacity but may make startup too tight.','72', {inputType:'number',min:0,max:2147483647,step:1,defaultValue:words('0 · 引擎自动估算','0 · automatic engine estimate')}),
  field('--host-cache-mib','主机缓存预算 · MiB','Host cache budget · MiB','使用 CPU 内存保存可复用 KV 和状态快照，不是 GPU 显存扩容。更大可保留更多前缀，但增加锁页 RAM 和传输开销；0 不建立 Host tier。Windows Shared 基线可能包含这部分。','CPU RAM for reusable KV and state snapshots, not extra GPU capacity. More retains more prefixes but consumes pinned RAM and transfer work. Zero disables the Host tier. This allocation may appear in the Windows Shared baseline.','6144', {inputType:'number',min:0,max:2147483647,step:1,defaultValue:words('8192','8192')}),
  field('--device-snapshot-slots','GPU 状态快照槽位','GPU snapshot slots','混合前缀缓存保留的 GPU 状态快照数量，范围 1–64，0 无效。增大可能提高分支复用机会，同时增加显存占用；留空时由并发及 Host tier 决定默认值。','GPU state snapshots retained by the hybrid cache, from 1 to 64; zero is invalid. More slots may improve branch reuse but consume VRAM. When omitted, the default depends on concurrency and the Host tier.','1', {inputType:'number',min:1,max:64,step:1,defaultValue:words('并发数 + 1；无 Host 缓存时 + 2','Concurrency + 1; + 2 without a Host cache')}),
  flag('--gdn-state-fp16','GDN 状态使用 FP16','FP16 GDN state','用 FP16 保存循环状态，减少该部分设备与主机快照内存。关闭恢复默认精度，内存可能增加。它改变状态存储精度，不会将模型权重转换成 FP16。','Stores recurrent state in FP16, reducing that part of GPU and host snapshot memory. Disabling restores the default precision and may increase memory use. This affects state storage, not model weight precision.'),
 ]},
 { title:words('KV 精度尾巴（precision tail）','KV precision tail'), fields:[
  numeric('--kv-tail-tokens','精确尾巴长度 · tokens','Exact tail length · tokens','把每个序列最近的 N 个 token 的 K/V 以未量化形式另存到设备端精确环，attention 时与量化 body 各算一次 FP32 partial，再做 online-softmax 合并。0 关闭（默认，行为与移植前逐字节相同）。开启后仅对 bf16 与 INT8 族（int8 / rk8v4 / rk4v4 / rk4v4-e8 / rk2v4-e8）真正参与合并；fp8 / nvfp4 / k8v4 会分配但惰性（开与关字节一致）。只在 small-T 解码路由（query 宽度 ≤ 8）合并，prefill 只写不合并；草稿（MTP）缓存按构造不含尾巴，所以只让验证器更准。设备常驻显存约 round_up(N,64)×65,536×并发 字节（N=1024、并发 1 时为 64 MiB），另有单页回滚预留；开启后解码约 −6%，收益随 body 量化变粗单调增大。','Keeps the newest N tokens of every sequence as unquantized K/V in a device-only exact ring; attention computes an FP32 partial for the quantized body and one for the exact tail, then merges them with online softmax. Zero disables it (the default, byte-identical to the pre-port path). When enabled, only bf16 and the INT8 family (int8 / rk8v4 / rk4v4 / rk4v4-e8 / rk2v4-e8) actually merge; fp8 / nvfp4 / k8v4 allocate but stay inert (identical bytes either way). Only the small-T decode route (query width ≤ 8) merges; prefill writes only. The MTP draft cache has no tail by construction, so this only sharpens the verifier. Resident device memory is about round_up(N,64)×65,536×concurrency bytes (64 MiB at N=1024, concurrency 1) plus one page of rollback reserve; decode costs about −6%, and the benefit grows with a coarser body.',0,2147483647,words('0 · 关闭','0 · off'),'1024'),
  choice('--kv-tail-type','精确环元素类型','Exact-tail element type','精确环保存 K/V 的元素类型。f16 有 10 位尾数，精度更高，是默认；bf16 只有 7 位尾数，是链路/对照验证形态。两者同为 16-bit，池大小、页几何与显存统计完全相同，所以选择不影响显存，只影响数值。仅在精确尾巴长度大于 0 时有意义，长度关闭时填写会被拒绝。','Element type of the exact ring. f16 has 10 mantissa bits and is more precise, the default; bf16 has 7 mantissa bits and is the split-verification form. Both are 16-bit, so pool size, page geometry and memory accounting are identical; the choice changes numerics only. It is meaningful only with a positive exact-tail length and is rejected while the tail is disabled.',[{value:'',label:words('引擎默认 · f16','Engine default · f16')},{value:'f16',label:words('f16 · 10 位尾数','f16 · 10 mantissa bits')},{value:'bf16',label:words('bf16 · 7 位尾数','bf16 · 7 mantissa bits')}],words('f16','f16')),
 ]},
 { title:words('草稿加速','Speculative decoding'), fields:[
  choice('--spec','草稿后端','Draft backend','先提出若干可能的后续 token，再由主模型验证。mtp 需要模型内置 MTP；dflash / dflash2 需要对应草稿组件。默认关闭；启用后须填写 1–15 个草稿。关闭只移除 --spec，保留其他设置供你调整；已填写的依赖参数必须一起满足引擎规则。效果取决于接受率，并不保证更快。','Proposes likely next tokens for verification by the main model. mtp needs an embedded MTP component; dflash / dflash2 need their matching draft component. Off by default; when enabled, set 1–15 drafts. Selecting Off removes only --spec and preserves other settings for you to adjust to engine requirements. Speed depends on acceptance and is not guaranteed.',[{value:'',label:words('关闭（引擎默认）','Off (engine default)')},{value:'mtp',label:words('MTP · 模型内置草稿','MTP · embedded drafter')},{value:'dflash',label:words('DFlash','DFlash')},{value:'dflash2',label:words('DFlash 2','DFlash 2')}],words('关闭','Off')),
  numeric('--draft-tokens','每轮草稿数','Drafts per round','启用草稿后端时必须填写 1–15。更多草稿可能一次接受更多 token，也增加草稿和验证开销。未启用后端时留空或 0；不能只把这里改成 0 来关闭已启用的后端。','Set 1–15 when a draft backend is enabled. More drafts may accept more tokens together but add proposal and verification work. With no backend, omit it or use zero. Zero does not turn off an enabled backend.',0,15,words('0；启用后端时须设为 1–15','0; set 1–15 when a backend is enabled'),'2'),
  flag('--lm-head-draft','优化草稿输出头','Optimized draft head','使用优化的 proposal head 生成草稿。是否更快取决于模型及内核路线；当前最终配置关闭。不会改变主模型最终验证的流程。','Uses the optimized proposal head for drafts. Speed depends on the model and kernel route; the current final profile leaves it off. Main-model verification remains in place.'),
  flag('--adaptive-mtp','自动调整 MTP 草稿宽度','Adaptive MTP width','仅适用于 mtp。根据实际接受情况与每轮耗时调整验证草稿数，通常在 3 到草稿上限之间；上限为 1 或 2 时仍合法，只能在该上限内工作。默认关闭。贪心解码结果不变，但不保证随机采样输出逐字一致。','For mtp only. Uses measured acceptance and round cost to adjust how many drafts are verified, normally between 3 and the configured maximum. A maximum of 1 or 2 is still valid and limits its width. Off by default. Greedy output is unchanged; this does not promise identical sampled text.'),
  numeric('--mtp-attention-window','MTP 注意力窗口 · tokens','MTP attention window · tokens','MTP 草稿头只看最前 64 个 key 与查询前最近 N 个 key；主模型验证仍看完整历史。0 使用完整历史。非零时须选择 mtp，且窗口至少为每轮草稿数 + 1。缩小可能减少长上下文开销，也可能降低接受率。','The MTP head attends to its first 64 keys and the newest N keys before its query; verification still sees the full history. Zero uses full history. A nonzero window requires mtp and at least drafts-per-round + 1 keys. Smaller windows may reduce long-context work but lower acceptance.',0,2147483647,words('0 · 完整历史','0 · full history'),'0'),
  numeric('--ngram-draft-tokens','复制草稿上限 · tokens','Copied drafts · token limit','从之前的提示、工具结果或输出中复制匹配片段，再与所选草稿后端一起验证，适合重复代码等场景。0 关闭；1–63 开启且需要草稿后端，超过 15 必须单并发。启用 --spec 且此项留空时默认 15。更大不保证更快。','Copies matching text from earlier prompts, tool results or output and verifies it alongside the draft backend. Repeated code may benefit. Zero disables it; 1–63 requires a backend, and above 15 requires one concurrent request. Omitted with --spec, it defaults to 15. More does not guarantee faster inference.',0,63,words('启用后端时 15；否则 0','15 with a backend; otherwise 0'),'31'),
  numeric('--ngram-min-match','复制所需最短匹配 · tokens','Minimum copy match · tokens','找到至少这么长的相同片段后才尝试复制其后内容。范围 4–64，默认 12。较小更容易匹配，也可能提出更多无效草稿；较大更保守。复制草稿关闭时不会产生复制效果。','Attempts to copy what follows a matching sequence of at least this length. Range 4–64, default 12. Smaller values find more matches but may produce more rejected drafts; larger values are more selective. It has no copy effect while ngram drafting is off.',4,64,words('12','12'),'12'),
  numeric('--ngram-archive-mib','跨请求复制来源 · MiB','Cross-request copy archive · MiB','用 CPU 内存保存已完成请求的可复制文本，供后来携带同一个 X-NInfer-Draft-Session 的请求复用；这不是 KV 缓存。0 关闭。开启时必须启用复制草稿，且每会话预算必须在 1 到总预算之间。','Keeps copy-source text from finished requests in CPU RAM for later requests with the same X-NInfer-Draft-Session. This is not a KV cache. Zero disables it. A positive budget requires ngram drafting and a per-session budget between 1 MiB and this total.',0,17592186044415,words('0 · 关闭','0 · off'),'0'),
  numeric('--ngram-session-mib','每会话复制来源上限 · MiB','Copy archive per session · MiB','每个会话最多占用多少跨请求复制来源内存。默认 128 MiB。总档案预算开启时此值必须至少 1，且不能超过总预算；不会额外再分配一份同样大小的 GPU 缓存。','Maximum cross-request copy-source memory for one session. Default 128 MiB. With an active archive it must be at least 1 MiB and no larger than the total archive budget. It does not create another GPU cache.',0,17592186044415,words('128','128'),'128'),
  flag('--ngram-native-sessions','识别客户端会话标识','Recognize client session IDs','除 X-NInfer-Draft-Session 外，也识别 Kilo、Codex、Claude 发送的会话标识，以便跨请求复用复制来源。默认关闭；开启前须把跨请求复制来源预算设为大于 0。不会自行创建或恢复客户端的对话历史。','Also recognizes session identifiers sent by Kilo, Codex and Claude, in addition to X-NInfer-Draft-Session, for reusing copy sources across requests. Off by default; requires a positive archive budget. It does not create or restore the client conversation history.'),
  numeric('--lookup-ngram','上下文查找匹配长度 · tokens','Context lookup match · tokens','用最后 N 个 token 在当前序列中查找相同片段，提议其后出现过的内容并验证。0 关闭。当前执行路线只在 MTP 后端使用它；未选 MTP 时允许保存这个值，但不会因此启用查找加速，DFlash 也不使用它。与跨请求复制档案是不同机制。','Matches the last N tokens against the current sequence, proposes what followed and verifies it. Zero disables it. The current execution path uses this only with MTP. The value can be saved without MTP, but that does not enable lookup acceleration; DFlash does not use it either. This differs from the cross-request copy archive.',0,2147483647,words('0 · 关闭','0 · off'),'0'),
 ]},
 { title:words('图片与视频','Images and video'), fields:[
  flag('--vision','启用图片与视频输入','Enable image and video input','允许接收图片和视频并加载视觉组件，默认关闭。模型必须包含 Vision 组件；只有 text / MTP 的模型不能通过此开关补出视觉能力。当前 strict / mixed 只支持纯文本，启用视觉前须手动选择 default 显存策略。','Accepts images and video and loads Vision resources; off by default. The model must contain a Vision component. This switch cannot add vision to a text / MTP-only artifact. Current strict / mixed policies are text-only; select default memory policy yourself before enabling vision.'),
  choice('--vision-residency','视觉组件放置位置','Vision component placement','resident 把视觉组件常驻 GPU；overlay 把视觉塔保存在主机内存，处理图片时临时借用设备内存，需要 CUDA VMM；cpu 在 CPU 上编码图片，不占用设备 Vision 内存，通常更慢。overlay / cpu 需要启用视觉。--vision-offload on/off 分别是 overlay/resident 的别名，可在高级选项中查看。','resident keeps Vision on the GPU. overlay holds the tower in host memory and temporarily borrows device memory per image, requiring CUDA VMM. cpu encodes images on CPU threads without device Vision allocations and is usually slower. overlay / cpu require vision to be enabled. --vision-offload on/off aliases overlay/resident and is available in advanced options.',[{value:'',label:words('引擎默认 · GPU 常驻','Engine default · GPU resident')},{value:'resident',label:words('GPU 常驻 · resident','GPU resident · resident')},{value:'overlay',label:words('按图片借用 GPU · overlay','Borrow GPU per image · overlay')},{value:'cpu',label:words('CPU 编码 · cpu','CPU encoding · cpu')}],words('resident · GPU 常驻','resident · GPU resident')),
  flag('--vision-cpu','快捷开启 CPU 视觉','CPU vision shortcut','等价于 --vision 加 --vision-residency cpu。勾选会同步这两项；取消此快捷开关会保留视觉开启并切回 resident。CPU 模式未填写视觉 token 上限时使用 256；明确填写后以填写值为准。不是 CPU 运行整个语言模型。','Equivalent to --vision plus --vision-residency cpu. Checking it updates both settings; unchecking keeps vision enabled and returns to resident. With CPU vision, the omitted merged-token limit becomes 256; an explicit value overrides it. This does not run the whole language model on the CPU.'),
  numeric('--vision-max-merged','每项媒体的视觉 token 上限','Vision tokens per media item','一张图片或一个媒体项目合并后的 token 上限，范围 64–16384。超过时会缩小媒体尺寸。较高可保留更多细节，但增加处理时间、上下文和内存开销。默认 16384；CPU 视觉未显式设置时默认 256。','Merged-token ceiling for one image or media item, from 64 to 16384. Larger media is downscaled. Higher values retain more detail but increase processing time, context use and memory. Default 16384; CPU vision uses 256 when this option is omitted.',64,16384,words('16384；CPU 视觉为 256','16384; CPU vision: 256'),'16384 / 256'),
  numeric('--media-cache-mib','已处理媒体缓存 · MiB','Prepared media cache · MiB','保留预处理好的媒体，供重复输入复用。使用主机内存，默认 1024 MiB；0 关闭保留缓存。增大有助于重复图片复用，不会提高首次处理速度。','Retains prepared media for repeated inputs in host memory. Default 1024 MiB; zero disables retained caching. A larger budget helps repeated media reuse, not first-time processing.',0,17592186044415,words('1024','1024'),'1024'),
  numeric('--media-live-mib','活跃媒体总预算 · MiB','Live prepared media budget · MiB','所有仍在使用的预处理媒体数据的总内存预算，默认 2048 MiB，须大于 0。包含正在处理请求持有的数据；它不同于只保留可复用项目的媒体缓存。过小可能拒绝较大媒体请求。','Total memory budget for all live prepared-media payloads, including data held by active requests. Default 2048 MiB; must be positive. This differs from the retained reuse cache. Too small a budget may reject large media requests.',1,17592186044415,words('2048','2048'),'2048'),
  numeric('--media-preprocess-threads','媒体预处理线程数','Media preprocessing workers','解码和预处理媒体的工作线程数量。0 自动选择，自动时最多 16；也可明确设置 1–64。更多线程可能提高并行处理速度，也会占用更多 CPU。它不是语言模型的 CPU 推理线程数。','Workers for media decoding and preprocessing. Zero selects automatically, up to 16 workers; explicit values may be 1–64. More workers may improve parallel preparation while using more CPU. This is not the language model’s CPU inference-thread count.',0,64,words('0 · 自动（最多 16）','0 · auto (up to 16)'),'0'),
 ]},
 { title:words('采样与思考','Sampling and reasoning'), fields:[
  field('--temperature','随机程度 · Temperature','Temperature','范围 0–2。较高通常更随机，较低更集中；0 选择最高概率 token。服务默认值可被请求覆盖，不是直接的速度档位。','Range 0–2. Higher is generally more random, lower more focused; zero picks the highest-probability token. Requests may override this default. It is not a direct speed setting.','1.0', {inputType:'number',min:0,max:2,step:0.01}),
  field('--top-p','累计概率 · Top P','Top P','范围 0–1，只保留累计概率达到阈值的候选。降低通常收窄选择；1 不做这项截断。0 是极窄阈值，不是关闭；与其他采样过滤共同作用。','Range 0–1. Keeps candidates up to a cumulative-probability threshold. Lower values narrow choices; 1 removes this cutoff. Zero is an extremely narrow threshold, not off. It combines with other sampling filters.','0.95', {inputType:'number',min:0,max:1,step:0.01}),
  field('--top-k','候选数量 · Top K','Top K','保留最可能的 K 个候选，本引擎范围 0–20。较小更集中；0 禁用 Top K 筛选。不会增加模型上下文或显存容量。','Keeps the K most likely candidates; this engine accepts 0–20. Smaller values focus sampling; zero disables Top K. It does not increase context or VRAM capacity.','20', {inputType:'number',min:0,max:20,step:1}),
  field('--min-p','相对概率 · Min P','Min P','范围 0–1，以最高概率候选为参照删除过低概率候选。增大过滤更强；0 关闭这项过滤。与 Top P / Top K 同时生效。','Range 0–1. Removes candidates whose probability is too small relative to the best candidate. Higher means stronger filtering; zero disables it. It combines with Top P and Top K.','0', {inputType:'number',min:0,max:1,step:0.01}),
  field('--presence-penalty','出现惩罚','Presence penalty','范围 -2–2。正值抑制已经出现过的 token，负值更鼓励再次出现；0 不加惩罚。代码中的必要重复也可能受影响，不建议为追求速度而提高。','Range -2–2. Positive values discourage previously seen tokens; negative values encourage repetition. Zero adds no penalty. Necessary code repetition can be affected; raising it is not a speed optimization.','0', {inputType:'number',min:-2,max:2,step:0.01}),
  field('--frequency-penalty','频次惩罚','Frequency penalty','范围 -2–2，按 token 已出现次数施加惩罚。正值更强地抑制频繁重复，负值鼓励；0 不加惩罚。与 presence penalty 不是同一个规则。','Range -2–2. Applies a penalty based on how often a token has appeared. Positive values discourage frequent repetition, negative values encourage it, and zero adds none. This differs from presence penalty.','0', {inputType:'number',min:-2,max:2,step:0.01}),
  field('--seed','默认随机种子','Default random seed','请求未指定 seed 时使用。固定值便于对比相同输入；0 也是固定种子，不是随机。清空表示每个请求重新生成种子。GPU执行等因素仍可能影响复现。','Used when a request omits its seed. A fixed value helps compare identical inputs. Zero is also a fixed seed, not random. Clear it for a fresh seed per request. GPU execution and other factors may still affect reproducibility.','42'),
  field('--default-reasoning-effort','默认思考强度','Default reasoning effort','客户端未指定时的思考级别，例如 low、medium、high、xhigh。较高通常允许更多推理，但不保证准确率或固定思考长度；仍受输出和上下文上限约束。实际行为依模型模板。','Reasoning level when the client omits it, such as low, medium, high or xhigh. Higher generally allows more reasoning but guarantees neither accuracy nor a fixed length. Output and context limits still apply. Exact behavior depends on the model template.','xhigh', {choices:[{value:'',label:words('由请求 / 模板决定','Request / template default')},...['none','minimal','low','medium','high','xhigh','max'].map(value=>({value,label:words(value,value)}))]}),
  flag('--preserve-thinking','保留历史思考','Preserve previous reasoning','在模板允许的情况下保留历史思考内容供后续请求使用，有助于维持推理上下文，但会占用更多输入 token。关闭不等于禁止模型本轮思考。','Retains previous reasoning where the template allows it. This may preserve reasoning context but consumes more input tokens. Disabling it does not turn off reasoning for the current request.'),
 ]},
 { title:words('模板与设备路线','Template and device routes'), fields:[
  field('--chat-template','对话模板路径','Chat template path','启动时替换模型自带 Jinja 对话模板，影响角色、工具调用和思考内容的组织。清空使用模型内置模板。config/ 开头的相对路径使用当前数据目录中的配置；其他相对路径从程序目录解析，绝对路径保持原样。错误模板可能导致请求被拒绝。','Replaces the embedded Jinja chat template at startup, controlling roles, tool calls and reasoning formatting. Clear it to use the embedded template. Relative config/ paths use the active data directory; other relative paths start at the package root, and absolute paths are unchanged. Invalid templates may reject requests.','config/chat_template.jinja'),
  field('--device-profile','设备路线选择','Device profile mode','auto 使用已有设备 profile 或内置路线，设备没有 profile 时可校准；off 使用编译内置路线；calibrate 重新测量并保存。校准会增加启动耗时，也不保证更快。','auto uses a stored or built-in profile and may calibrate an unknown device. off uses compiled routes. calibrate measures and saves new routes. Calibration increases startup time and does not guarantee better performance.','auto', {choices:[{value:'',label:words('引擎默认 · auto','Engine default · auto')},{value:'auto',label:words('自动选择 · auto','Select automatically · auto')},{value:'off',label:words('编译内置路线 · off','Compiled routes · off')},{value:'calibrate',label:words('重新测量 · calibrate','Measure again · calibrate')}],defaultValue:words('auto','auto')}),
  field('--device-profile-path','设备 profile 文件','Device profile file','保存或读取 GPU 内核选择的文件。当前独立副本保留已验证路线；换文件可能改变内核选择和性能。config/ 开头的相对路径使用当前数据目录；绝对路径保持原样。清空由引擎使用默认用户缓存位置。','File for GPU kernel-route profiles. The current independent copy preserves validated routes. A different file may change kernel selection and performance. Relative config/ paths use the active data directory; absolute paths are unchanged. Clear it to use the engine’s default user-cache location.','config/device-profiles.json'),
 ]},
]
